import { get } from "svelte/store";

export const ENDPOINTS = {
    connectToken: '/connect/token',
    getMe: '/api/app/users/me',
    getFormPaging: '/api/core/form',
    getGvLayout: '/api/core/form-layout',
    getGvLayoutForAdmin :`/api/core/form-layout/admin`,
    updateFormContent: (idForm: number) => `/api/core/form/${idForm}/form-content`,
    deleteRowTableData: '/api/core/form/row-table',
    downloadForm : (idForm: number) => `/api/core/form-template/form-loai/${idForm}/replace`,
    createForm: '/api/core/form',
    getToChucPaging :'/api/core/to-chuc',
    createToChuc : '/api/core/to-chuc',
    deleteToChuc : (idToChuc: number) => `/api/core/to-chuc/${idToChuc}`,
    getPagingNhanVienToChuc: '/api/core/to-chuc/nhan-vien',
    getListDropDownForm: '/api/core/form/list-drop-down',
    updateFormContentAdmin:  `/api/core/form/admin/form-content`,
    deleteRowTableDataAdmin: '/api/core/form/row-table',
    downloadFormAdmin: '/api/core/form-template/admin/replace',
    getReportTotalNhanVienToChuc: (idFormLoai:number) => `/api/core/thong-ke/form-loai/${idFormLoai}/nhan-vien`,
    getReportNhanVienToChucPaging: (idFormLoai:number) => `/api/core/thong-ke/form-loai/${idFormLoai}/to-chuc/paging`,
    getReportNhanVienByToChucPaging: (idFormLoai:number, idToChuc:number) => `/api/core/thong-ke/form-loai/${idFormLoai}/to-chuc/${idToChuc}/nhan-vien/paging`,
    getDashboardData: '/api/core/thong-ke/dashboard',
}